// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadXid returns the embedded CollectionSpec for xid.
func loadXid() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_XidBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load xid: %w", err)
	}

	return spec, err
}

// loadXidObjects loads xid and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*xidObjects
//	*xidPrograms
//	*xidMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadXidObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadXid()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// xidSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xidSpecs struct {
	xidProgramSpecs
	xidMapSpecs
}

// xidSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xidProgramSpecs struct {
	HandleNvidiaXid *ebpf.ProgramSpec `ebpf:"handle_nvidia_xid"`
}

// xidMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xidMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// xidObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadXidObjects or ebpf.CollectionSpec.LoadAndAssign.
type xidObjects struct {
	xidPrograms
	xidMaps
}

func (o *xidObjects) Close() error {
	return _XidClose(
		&o.xidPrograms,
		&o.xidMaps,
	)
}

// xidMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadXidObjects or ebpf.CollectionSpec.LoadAndAssign.
type xidMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *xidMaps) Close() error {
	return _XidClose(
		m.Events,
	)
}

// xidPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadXidObjects or ebpf.CollectionSpec.LoadAndAssign.
type xidPrograms struct {
	HandleNvidiaXid *ebpf.Program `ebpf:"handle_nvidia_xid"`
}

func (p *xidPrograms) Close() error {
	return _XidClose(
		p.HandleNvidiaXid,
	)
}

func _XidClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed xid_bpfel_x86.o
var _XidBytes []byte
